## joint_names
##joint_names: [orthos_motor_left_1_joint, orthos_motor_right_1_joint, orthos_motor_left_2_joint, orthos_motor_right_2_joint, orthos_motor_left_3_joint, orthos_motor_right_3_joint]

## control_mode_adapter
#max_command_silence: 0.5



## position controller
#orthos_position_controller_7:
#  type: position_controllers/JointPositionController
#  joint: base_link_1_joint
#  required_drive_mode: 1 #Profile Position mode 6060
#  
#orthos_position_controller_8:
#  type: position_controllers/JointPositionController
#  joint: link_1_link_2_joint
#  required_drive_mode: 1 #Profile Position mode 6060

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100


kackmotor_controller:
  type: position_controllers/JointPositionController
  joint: atalante_arm_shoulder_joint
  required_drive_mode: 1

#kackmotor_controller:
#  type: position_controllers/JointTrajectoryController
#  joints:
#    - shoulder_joint
#  required_drive_mode: 1



  
  
  


    
      

